blank_issues_enabled: false
contact_links:
  - name: 📖 Documentation
    url: https://github.com/ironsheep/P2-FLASH-FS
    about: Supporting Documentation is all at the repository README
  - name: 📖 Forum Thread
    url: https://forums.parallax.com/discussion/175470/on-board-flash-file-system#latest
    about: Join us in this forum for discussion and support
