#!/bin/bash

#SRC_SPIN_DIR="/Users/stephen/Library/CloudStorage/Dropbox/PropV2-Shared/FmToPeople/fmChip/NewFlashFS/VERSION-PREP"
SRC_SPIN_DIR="/Users/stephen/Library/CloudStorage/Dropbox/PropV2-Shared/FmToPeople/fmChip/NewFlashFS/driver-reWork-SMM"
DST_SPIN_DIR="/Users/stephen/Projects/Projects-ExtGit/IronSheepProductionsLLC/Projects P2/P2-Flash-FS/P2-FLASH-FS/REF"

for FIL in `ls -1 "${DST_SPIN_DIR}" | grep \.spin2`; do
        filename=`basename "${FIL}"`
        #echo "Checking FILE: ${filename}"
        #(set -x;md5 -q "${FIL}")
        #(set -x;md5 -q "${filename}")
        if [ -f "${filename}" ]; then
                RMTE_SUM=`md5 -q "${FIL}"`
                LOCL_SUM=`md5 -q "${filename}"`
                # compare the two sums
                if [ "$LOCL_SUM" != "$RMTE_SUM" ]; then
                        echo "- ${RMTE_SUM} : ${LOCL_SUM} : DIFFERENT  [${filename}]"
                        (set -x; diff "$FIL" "${filename}")
                else
                        echo "* ${RMTE_SUM} : ${LOCL_SUM} : MATCH    [${filename}]"
                fi
        fi

done
