#!/bin/bash

SRC_SPIN_DIR="/Users/stephen/Library/CloudStorage/Dropbox/PropV2-Shared/FmToPeople/fmChip/NewFlashFS/VERSION-PREP"
DST_SPIN_DIR="/Users/stephen/Projects/Projects-ExtGit/IronSheepProductionsLLC/Projects P2/P2-Flash-FS/P2-FLASH-FS/REF"

(set -x;cp -p "${SRC_SPIN_DIR}"/*.spin2 "${DST_SPIN_DIR}")
