#!/bin/bash

#SRC_SPIN_DIR="/Users/stephen/Library/CloudStorage/Dropbox/PropV2-Shared/FmToPeople/fmChip/NewFlashFS/VERSION-PREP"
SRC_SPIN_DIR="/Users/stephen/Library/CloudStorage/Dropbox/PropV2-Shared/FmToPeople/fmChip/NewFlashFS/driver-reWork-SMM"
DST_SPIN_DIR="/Users/stephen/Projects/Projects-ExtGit/IronSheepProductionsLLC/Propeller2/P2-FLASH-FileSystem/P2-FLASH-FS/REF"

for FIL in `ls -1 "${DST_SPIN_DIR}" | egrep -v OLD | grep \.spin2`; do
        filename=`basename "${FIL}"`
        SRC_FIL=${SRC_SPIN_DIR}/${filename}
        DST_FIL=${DST_SPIN_DIR}/${filename}
        #echo "Checking FILE: ${filename}"
        #(set -x;md5 -q "${FIL}")
        #(set -x;md5 -q "${filename}")
        if [ -f "${filename}" ]; then
                SRC_SUM=`md5 -q "${SRC_FIL}"`
                DST_SUM=`md5 -q "${DST_FIL}"`
                # compare the two sums
                if [ "$DST_SUM" != "$SRC_SUM" ]; then
                        echo "- ${SRC_SUM} : ${DST_SUM} : DIFFERENT  [${filename}]"
                        (set -x; cp -p "$SRC_FIL" "${DST_FIL}")
                else
                        echo "* ${SRC_SUM} : ${DST_SUM} : MATCH    [${filename}]"
                fi
        fi

done
